FROM jenkins/jenkins:lts

USER root
RUN apt-get update && \
    apt-get install -y \
    docker.io \
    git \
    sudo \
    && rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker jenkins

USER jenkins

EXPOSE 8080

CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
